version: "3.8"

services:
  back-end:
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "5000:5000"
    networks:
      - mbi-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - PORT=5000
      - MSSQL=host.docker.internal:1433
    extra_hosts:
      - "homeoffice:127.0.0.1"
      - host.docker.internal:host-gateway
    stdin_open: true
    tty: true
  front-end:
    build:
      context: ../../mbi-front-end
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ../../mbi-front-end/.env.docker
    ports:
      - "3000:3000"
    networks:
      - mbi-network
    environment:
      - PORT=3000
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysqldb" ]
      timeout: 20s
      retries: 10
    networks:
      - mbi-network

networks:
  mbi-network:
    name: mbi-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.125.0.0/24
          gateway: 172.125.0.1
volumes:
  db: