#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 5000:5000
#    networks:
#      - springapimysql-net
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/BIServer?allowPublicKeyRetrieval=true
#    depends_on:
#      - mysqldb
#    volumes:
#      - .m2:/root/.m2
#
#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3306:3306
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: BIServer
#      MYSQL_USER: almeida
#      MYSQL_PASSWORD: thomas
#      MYSQL_ROOT_PASSWORD: thomas
#networks:
#  springapimysql-net:

#version: "3.8"
#
#services:
#  mysqldb:
#    image: mysql:8.0
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/mysql
#  app:
#    depends_on:
#      - mysqldb
#    build: .
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#        "spring.datasource.username" : "$MYSQLDB_USER",
#        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#        "spring.jpa.hibernate.ddl-auto" : "update"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true
#
#volumes:
#  db:

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=BIServer'
      - 'MYSQL_PASSWORD=almeida'
      - 'MYSQL_USER=thomas'
      - 'MYSQL_ROOT_PASSWORD=thomas'

    ports:
      - '3307:3307'
  application:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/BIServer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: almeida
      SPRING_DATASOURCE_PASSWORD: thomas
volumes:
  mysql-data: