INSERT INTO bi_interface(id, name) VALUES(1, 'Administração');
INSERT INTO bi_interface(id, name) VALUES(2, 'Análise');
INSERT INTO bi_interface(id, name) VALUES(3, 'Campos da Análise');
INSERT INTO bi_interface(id, name) VALUES(4, 'Usuário');
INSERT INTO bi_interface(id, name) VALUES(5, 'Configuracao do e-mail');
-- INSERT INTO bi_interface(id, name) VALUES(6, 'Atualizacao BI');
-- INSERT INTO bi_interface(id, name) VALUES(7, 'Cliente');
INSERT INTO bi_interface(id, name) VALUES(8, 'Painel');
INSERT INTO bi_interface(id, name) VALUES(9, 'Conexões das Análises');
INSERT INTO bi_interface(id, name) VALUES(10, 'Campos da Análise do Painel');
-- INSERT INTO bi_interface(id, name) VALUES(11, 'GPE');
INSERT INTO bi_interface(id, name) VALUES(12, 'Painel - RecarregarAnálise');
INSERT INTO bi_interface(id, name) VALUES(13, 'Painel - Importar Análises');
INSERT INTO bi_interface(id, name) VALUES(14, 'Painel - Arquivo');
INSERT INTO bi_interface(id, name) VALUES(15, 'Painel - Campos');
INSERT INTO bi_interface(id, name) VALUES(16, 'Painel - Cores');;
INSERT INTO bi_interface(id, name) VALUES(17, 'Painel - Gráficos');
INSERT INTO bi_interface(id, name) VALUES(18, 'Painel - Gerar Planilha Excel');
INSERT INTO bi_interface(id, name) VALUES(19, 'Painel - Incluir Campo na Sequência');
INSERT INTO bi_interface(id, name) VALUES(20, 'Painel - Agregações');
INSERT INTO bi_interface(id, name) VALUES(21, 'Painel - Ordenação');
INSERT INTO bi_interface(id, name) VALUES(22, 'Painel - Sequência de Visualização');
INSERT INTO bi_interface(id, name) VALUES(23, 'Painel - Sequência de Filtros');
INSERT INTO bi_interface(id, name) VALUES(24, 'Painel - Análise Vertical');
INSERT INTO bi_interface(id, name) VALUES(25, 'Painel - Análise Horizontal');
INSERT INTO bi_interface(id, name) VALUES(26, 'Painel - Totalização Parcial');
INSERT INTO bi_interface(id, name) VALUES(27, 'Painel - Casas Decimais');
INSERT INTO bi_interface(id, name) VALUES(28, 'Painel - Coluna Calculada');
-- INSERT INTO bi_interface(id, name) VALUES(29, 'Agentes Inteligentes');
-- INSERT INTO bi_interface(id, name) VALUES(30, 'GRL - Preferências');
-- INSERT INTO bi_interface(id, name) VALUES(31, 'GRL - Pastas Grupos Relatórios');
INSERT INTO bi_interface(id, name) VALUES(32, 'Agendamentos');
INSERT INTO bi_interface(id, name) VALUES(33, 'Slidshow');
INSERT INTO bi_interface(id, name) VALUES(34, 'Arquivos');