INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(1, 1, 1, 'Administração do Sistema');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(2, 2, 2, 'Consultar Análises próprias');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(3, 2, 4, 'Consultar todas as Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(4, 2, 8, 'Excluir Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(5, 2, 16, 'Incluir Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(6, 2, 1, 'Alterar Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(7, 3, 1, 'Alterar Campos das Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(8, 3, 2, 'Consultar Campos das Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(9, 3, 4, 'Excluir Campos das Análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(10, 3, 8, 'Incluir Campos das Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(11, 5, 1, 'Alterar configuracao e-mail');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(12, 5, 2, 'Consultar configuracao e-mail');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(13, 5, 4, 'Excluir configuracao e-mail');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(14, 5, 8, 'Incluir configuracao e-mail');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(15, 4, 1, 'Alterar Usuários');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(16, 4, 2, 'Consultar Usuários');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(17, 4, 4, 'Excluir Usuários');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(18, 4, 8, 'Incluir Usuários');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(19, 6, 1, 'Baixar e atualizar o BI');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(20, 7, 1, 'Alterar Cliente');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(21, 7, 2, 'Consultar Cliente');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(22, 7, 4, 'Excluir Cliente');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(23, 7, 8, 'Incluir Cliente');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(24, 8, 1, 'Alterar painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(25, 8, 2, 'Consultar painéis próprios');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(26, 8, 4, 'Consultar todos os painéis');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(27, 8, 8, 'Excluir painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(28, 8, 16, 'Excluir Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(29, 9, 1, 'Alterar conexões das análises');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(30, 10, 1, 'Alterar propriedades do Campo no painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(31, 10, 2, 'Alterar parte de Campos no Painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(32, 10, 4, 'Consultar Campos no Painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(33, 12, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(34, 13, 1, 'Análises do Repositório');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(35, 13, 2, 'Análises de Outros Painéis');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(36, 13, 4, 'Meus Arquivos');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(37, 13, 8, 'Meus Paineis');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(38, 14, 1, 'Salvar Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(39, 14, 2, 'Salvar Análise Como');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(40, 14, 4, 'Agendar Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(41, 14, 8, 'Enviar Análise por E-Mail');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(42, 14, 16, 'Restrições da Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(43, 14, 32, 'Imprimir Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(44, 14, 64, 'Excluir Análise');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(45, 14, 128, 'Salvar Painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(46, 14, 256, 'Salvar Painel Como');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(47, 14, 512, 'Excluir Painel');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(48, 15, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(49, 16, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(50, 17, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(51, 18, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(52, 19, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(53, 20, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(54, 21, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(55, 22, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(56, 23, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(57, 24, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(58, 25, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(59, 26, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(60, 27, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(61, 28, 1, 'Habilita botão');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(62, 11, 1, 'Habilita botão');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(63, 29, 1, 'Acessar');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(64, 30, 1, 'Habilita botão');
-- INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(65, 31, 1, 'Habilita botão');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(66, 14, 1024, 'Copiar URL');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES(67,33,1,'Criar slideshow');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES (68,2,32, 'Incluir Anexos');
INSERT INTO bi_interface_action(id, interface_id, action_weight, description) VALUES (69,34,1, 'Incluir Arquivos');